import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.kulinersince.com/">KulinerSince!</a>
        </h1>

        <p className={styles.description}>
          Khazanah kuliner di nusantara yang setidaknya sudah bertahan 20 tahun atau lebih hingga sekarang.
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://arifsetiawan.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by Arif Setiawan
        </a>
      </footer>
    </div>
  )
}

export default Home
